name: sns-inventory-backend

services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  cdn:
    image: python:3.11-slim
    ports:
      - "8001:8001"
    volumes:
      - ./localdevuploads:/root/localdevfiles/
    networks:
      - app-network
    entrypoint: python3 -m http.server 8001 -d /root/localdevuploads/

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
