"""empty message

Revision ID: af7ae6368a55
Revises: 11c780da6347
Create Date: 2026-07-19 04:20:09.409024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7ae6368a55'
down_revision: Union[str, Sequence[str], None] = '11c780da6347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.Text(), nullable=False))
    op.add_column('files', sa.Column('content_type', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'content_type')
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###
