"""empty message

Revision ID: e284a1681385
Revises: a1b2c3d4e5f6
Create Date: 2026-07-18 21:40:51.164230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e284a1681385'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_sub_categories')
    op.add_column('asset_categories', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('asset_categories', sa.Column('type', sa.Text(), nullable=False))
    op.alter_column('assets', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assets', 'permanent_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assets', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('assets', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('assets', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('assets', 'permanent_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assets', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('asset_categories', 'type')
    op.drop_column('asset_categories', 'id')
    op.create_table('asset_sub_categories',
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_sub_categories_asset_id_fkey')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('asset_sub_categories_category_id_fkey')),
    sa.PrimaryKeyConstraint('asset_id', 'category_id', name=op.f('asset_sub_categories_pkey'))
    )
    # ### end Alembic commands ###
