"""empty message

Revision ID: ee567c19b7e3
Revises: 3135f4278a25
Create Date: 2026-09-11 03:08:57.857342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee567c19b7e3'
down_revision: Union[str, Sequence[str], None] = '3135f4278a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('files', sa.Column('url', sa.Text(), nullable=False))
    op.add_column('files', sa.Column('filename', sa.Text(), nullable=False))
    op.add_column('files', sa.Column('system_filename', sa.Text(), nullable=False))
    op.add_column('files', sa.Column('content_type', sa.Text(), nullable=False))
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_column('files', 'content_type')
    op.drop_column('files', 'system_filename')
    op.drop_column('files', 'filename')
    op.drop_column('files', 'url')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    # ### end Alembic commands ###
